version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: house_price_paid_analysis
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: house_price_paid_analysis
      POSTGRES_HOST_AUTH_METHOD: trust 
    ports:
      - "5432:5432"
    volumes:
      - ./data:/imports
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
