services:
  postgres:
    image: postgres:latest
    container_name: house_price_paid_elt_pipeline
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: house_price_paid_elt_pipeline
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./data:/imports
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
